### PR TITLE
Update library dependencies

### PR DESCRIPTION
**Pull request by wyqydsyq**
- Update library dependencies to latest versions

I noticed that a couple of tests are failing when I did this and ran them, but then I checked out `master` and ran the tests and noticed there's even more that fail for me on current `master` so I guess this is also a step forwards there. Both the example and my own project work fine using the library with these bumped dependency versions so there shouldn't be any issues in practice.

Hopefully I'll have some spare time this weekend to take a look at updating the tests.

(This branch is forked from the one on https://github.com/Widdershin/cycle-restart/pull/63, may want to merge that one first)

### CODE REVIEW

**Comment by Widdershin** [comment]
I changed all the tests to use `@cycle/run` instead of `@cycle/xstream-run` and fixed all the resulting errors. Also updated the documentation to reflect that you need to pass `setup` to both `restart` and `restartable`.

Thanks for making this pull request. Thanks to your efforts we're now ready for a proper unified release.

**Comment by Widdershin** [comment]
@wyqydsyq I've invited you to be a collaborator on this repo. I appreciate the contributions that you've made 😄. If you accept, there's no obligation to spend any time on this project, but if you are interested in continuing to collaborate, it would mean you could work on branches on this repo, help review pull requests and triage issues and guide the future of the project.

**Comment by wyqydsyq** [comment]
Awesome, thanks.

I probably won't go out of my way to write additional code beyond the needs of my own use-cases, but I'm more than happy to help review Issues/PRs and participate in any discussion that crops up.

**Comment by Widdershin** [comment]
👍 sounds great. Any level of contribution is welcome 😄

**Pull request merged**
